name: Build and Deploy to Azure

on:
  push:
    branches:
      - toAzure  # Le workflow se déclenchera sur chaque push sur la branche 'toAzure'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # La machine virtuelle utilisée pour exécuter le workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Action pour récupérer le code source du dépôt

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Utilisation du JDK 17 pour compiler ton projet
          distribution: 'temurin'

      - name: Build Docker Image
        run: |
          docker build -t dodiefav/app-devops:${{ github.sha }} .

      - name: Docker Login
        uses: docker/login-action@v2  # Action pour se connecter à Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Utilisation du secret pour le login
          password: ${{ secrets.DOCKER_PASSWORD }}  # Utilisation du secret pour le mot de passe

      - name: Push Docker Image to Docker Hub
        run: |
          docker push dodiefav/app-devops:${{ github.sha }} 

    #   - name: Deploy to Azure
    #     uses: azure/webapps-deploy@v2  # Action pour déployer sur Azure Web Apps
    #     with:
    #       app-name: 'my-app-devops-ef'  # Remplace 'your-app-name' par le nom de ton application sur Azure
    #       publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Secret Azure Publish Profile
